# Generated by Django 4.2.9 on 2024-01-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cardTitle', models.CharField(max_length=50)),
                ('cardDescription', models.CharField(max_length=200)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
                ('cardImage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
