# Generated by Django 4.2.9 on 2024-01-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
