# Generated by Django 4.2.9 on 2024-01-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_delete_blogpost_blog_content_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
    ]
