# Generated by Django 4.2.9 on 2024-02-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_rename_blog_likes_blogpost_likes_countlikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='countLikes',
        ),
    ]
