# Generated by Django 4.2.9 on 2024-02-05 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='members.blog'),
            preserve_default=False,
        ),
    ]
